name: Pull Request
on:
  pull_request:
    types: [opened, labeled, synchronize, reopened]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Run tests
        run: go test -v ./...

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.22

      - name: Build for Linux
        run: GOOS=linux GOARCH=amd64 go build -v -o bw-cli-linux-amd64 .

      - name: Build for macOS
        run: GOOS=darwin GOARCH=arm64 go build -v -o bw-cli-darwin-arm64 .